input:
  label: httpserver001
  http_server:
    path: /post
    timeout: 20s
pipeline:
  processors:
    - switch:
        - check: meta("enqueue") == undefined
          processors:
            - bloblang: |
                meta enqueue = true

        - processors:
            - bloblang: |
                meta = deleted()
output:
  switch:
    - cases:
      - check: meta("enqueue") == undefined
      output:
        http_client:
          url: http://host.docker.internal:5264/payload
          verb: POST
          propagate_response: true
          batch_as_multipart: false
          rate_limit: rate10s
          headers:
            Content-Type: application/json
      output:
        - kafka:
            addresses: [ broker:29092 ]
            topic: foo_topic
    

rate_limit_resources:
  - label: rate10s
    local:
      count: 10
      interval: 1s
