---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    networks:
      - benthos-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - benthos-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - broker
    ports:
      - 19000:9000
    networks:
      - benthos-network
    environment:
      - KAFKA_BROKERCONNECT=broker:29092

  producer:
    image: jeffail/benthos:latest
    container_name: benthos-container-producer
    depends_on:
      - broker
    ports:
      - 8080:4195
    networks:
      - benthos-network
    volumes:
      - C:\dev\poc-benthos\config_httpServer_kafkaOutput.yaml:/benthos.yaml

  consumer:
    image: jeffail/benthos:latest
    container_name: benthos-container-consumer
    depends_on:
      - broker
    networks:
      - benthos-network
    volumes:
      - C:\dev\poc-benthos\config_kafkaMultipleConsumer_httpClient.yaml:/benthos.yaml

  prometheus:
    image: prom/prometheus:latest
    user: root
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/prometheus/config/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    networks:
      - benthos-network

    grafana:
      image: grafana/grafana
      container_name: grafana
      hostname: grafana
      environment:
        -  GF_SECURITY_ADMIN_PASSWORD=admin
      restart: unless-stopped
      ports:
        - 3000:3000
      networks:
        - benthos-network
      depends_on:
        - broker
        - consumer
        - producer
        - prometheus



  # jaeger:
  #   image: jaegertracing/all-in-one:1.33
  #   platform: linux/arm64
  #   container_name: jaeger
  #   restart: always
  #   ports:
  #     - "5775:5775/udp"
  #     - "6831:6831/udp"
  #     - "6832:6832/udp"
  #     - "5778:5778"
  #     - "16686:16686"
  #     - "14268:14268"
  #     - "9411:9411"
  #   networks:
  #     - benthos-network
  #   environment:
  #     - COLLECTOR_ZIPKIN_HTTP_PORT=9411



networks:
  benthos-network:
    name: benthos-network